/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supsoluti;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

/**
 *
 * @author brenno.lima
 */
public class T_cert_apagado extends javax.swing.JInternalFrame {

    /**
     * Creates new form T_cert_apagado
     */
    public T_cert_apagado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEquipamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMidia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDrive = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSisUso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCopiar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextsolitacao = new javax.swing.JTextField();
        jTextnome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextemail = new javax.swing.JTextField();
        jTextcidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextTelefone = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelemail = new javax.swing.JLabel();
        jLabelapagado = new javax.swing.JLabel();

        setTitle("Certificado Apagado");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Certificado apagado:"));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tipo do Equipamento:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 40, 130, 14);

        txtEquipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEquipamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEquipamentoKeyTyped(evt);
            }
        });
        jPanel1.add(txtEquipamento);
        txtEquipamento.setBounds(200, 30, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Marca e Modelo das Mídias:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 160, 14);

        txtMidia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMidia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMidiaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMidia);
        txtMidia.setBounds(200, 70, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Versão do drive utilizada:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 150, 14);

        txtDrive.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDrive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDriveKeyTyped(evt);
            }
        });
        jPanel1.add(txtDrive);
        txtDrive.setBounds(200, 110, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sistema operacional utilizado:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 160, 170, 14);

        txtSo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSo);
        txtSo.setBounds(200, 150, 210, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Sistemas de uso do certificado:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 180, 14);

        txtSisUso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSisUso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSisUsoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSisUso);
        txtSisUso.setBounds(200, 190, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Serial do equipamento:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 240, 130, 14);

        txtSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSerial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialKeyTyped(evt);
            }
        });
        jPanel1.add(txtSerial);
        txtSerial.setBounds(200, 230, 180, 30);

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(350, 40, 10, 14);

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(350, 120, 10, 14);

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(420, 80, 10, 14);

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(420, 160, 10, 14);

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(420, 200, 10, 14);

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(390, 240, 10, 14);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 440, 270);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/copiar.png"))); // NOI18N
        btnCopiar.setText("COPIAR");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 310, 437, 70);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail para Supervisor:"));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código da Solicitação:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(21, 70, 122, 14);

        jTextsolitacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextsolitacaoKeyTyped(evt);
            }
        });
        jPanel4.add(jTextsolitacao);
        jTextsolitacao.setBounds(150, 60, 180, 30);

        jTextnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextnomeKeyTyped(evt);
            }
        });
        jPanel4.add(jTextnome);
        jTextnome.setBounds(150, 100, 284, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nome:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(110, 110, 35, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("E-mail:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(105, 150, 38, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Telefone:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(90, 190, 52, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Cidade:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(101, 230, 41, 14);

        jTextemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextemailKeyTyped(evt);
            }
        });
        jPanel4.add(jTextemail);
        jTextemail.setBounds(150, 140, 284, 30);

        jTextcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextcidadeKeyTyped(evt);
            }
        });
        jPanel4.add(jTextcidade);
        jTextcidade.setBounds(150, 220, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Segue as informações do certificado apagado. ");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(16, 27, 270, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(440, 110, 10, 10);

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(340, 70, 10, 14);

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(440, 150, 10, 14);

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(340, 190, 10, 14);

        jTextTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefoneKeyTyped(evt);
            }
        });
        jPanel4.add(jTextTelefone);
        jTextTelefone.setBounds(150, 180, 180, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(460, 10, 460, 270);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/copiar.png"))); // NOI18N
        jButton1.setText("COPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        jButton2.setText("LIMPAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(460, 310, 457, 70);

        jLabelemail.setForeground(new java.awt.Color(0, 0, 255));
        jLabelemail.setText("...");
        jPanel2.add(jLabelemail);
        jLabelemail.setBounds(660, 290, 240, 14);

        jLabelapagado.setForeground(new java.awt.Color(0, 0, 255));
        jLabelapagado.setText("...");
        jPanel2.add(jLabelapagado);
        jLabelapagado.setBounds(160, 290, 270, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEquipamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquipamentoKeyTyped
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabelapagado.setText("...");
    }//GEN-LAST:event_txtEquipamentoKeyTyped

    private void txtMidiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMidiaKeyTyped
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabelapagado.setText("...");
    }//GEN-LAST:event_txtMidiaKeyTyped

    private void txtDriveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDriveKeyTyped
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabelapagado.setText("...");
    }//GEN-LAST:event_txtDriveKeyTyped

    private void txtSoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoKeyTyped
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabelapagado.setText("...");
    }//GEN-LAST:event_txtSoKeyTyped

    private void txtSisUsoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSisUsoKeyTyped
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabelapagado.setText("...");
    }//GEN-LAST:event_txtSisUsoKeyTyped

    private void txtSerialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialKeyTyped
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabelapagado.setText("...");
    }//GEN-LAST:event_txtSerialKeyTyped
    public void limparTela() {
        txtEquipamento.setText("");
        txtMidia.setText("");
        txtDrive.setText("");
        txtSo.setText("");
        txtSisUso.setText("");
        txtSerial.setText("");
        btnCopiar.setEnabled(false);
        btnLimpar.setEnabled(false);
    }
    private String copiarCertificadoApagado() {
        String dados = "*** CERTIFICADO APAGADO ***";
        dados += "\n- Tipo do equipamento: " + txtEquipamento.getText()
                + "\n- Marca e modelo das mídias: " + txtMidia.getText()
                + "\n- Versão do drive utilizada: " + txtDrive.getText()
                + "\n- Sistema operacional utilizado: " + txtSo.getText()
                + "\n- Sistemas de uso do certificado: " + txtSisUso.getText()
                + "\n- Serial do equipamento: " + txtSerial.getText();
        return dados;
    }

    private String copiarEmail() {
        String dados = "Segue as informações do certificado apagado.\n";
        dados += "\nSolicitação: " + jTextsolitacao.getText()
                + "\nNome: " + jTextnome.getText()
                + "\nE-mail: " + jTextemail.getText()
                + "\nTelefone: " + jTextTelefone.getText()
                + "\nCidade: " + jTextcidade.getText();
        return dados;
    }
    public void eCopiarCampos(boolean confere) {
        if (confere) {
            String d = copiarCertificadoApagado();
            Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
            ClipboardOwner selecao = new StringSelection(d);
            board.setContents((Transferable) selecao, selecao);
            //JOptionPane.showMessageDialog(this, "Copiado com Exito");
            jLabelapagado.setText("Copiado com Exito!");
        } else {
            String d = copiarEmail();
            Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
            ClipboardOwner selecao = new StringSelection(d);
            board.setContents((Transferable) selecao, selecao);
            //JOptionPane.showMessageDialog(this, "E-mail Copiado com Exito");
            jLabelemail.setText("E-mail Copiado com Exito!");
        }
    }
    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        eCopiarCampos(true);//chama função certificado apagado
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
        jLabelapagado.setText("...");
        txtEquipamento.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jTextsolitacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextsolitacaoKeyTyped
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jLabelemail.setText("...");
    }//GEN-LAST:event_jTextsolitacaoKeyTyped

    private void jTextnomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnomeKeyTyped
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jLabelemail.setText("...");
    }//GEN-LAST:event_jTextnomeKeyTyped

    private void jTextemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextemailKeyTyped
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jLabelemail.setText("...");
    }//GEN-LAST:event_jTextemailKeyTyped

    private void jTextcidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextcidadeKeyTyped
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jLabelemail.setText("...");
    }//GEN-LAST:event_jTextcidadeKeyTyped

    private void jTextTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefoneKeyTyped
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jLabelemail.setText("...");
    }//GEN-LAST:event_jTextTelefoneKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        eCopiarCampos(false);//chama função email
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextsolitacao.setText("");
        jTextnome.setText("");
        jTextemail.setText("");
        jTextTelefone.setText("");
        jTextcidade.setText("");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jLabelemail.setText("...");
        jTextsolitacao.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelapagado;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JTextField jTextcidade;
    private javax.swing.JTextField jTextemail;
    private javax.swing.JTextField jTextnome;
    private javax.swing.JTextField jTextsolitacao;
    private javax.swing.JTextField txtDrive;
    private javax.swing.JTextField txtEquipamento;
    private javax.swing.JTextField txtMidia;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtSisUso;
    private javax.swing.JTextField txtSo;
    // End of variables declaration//GEN-END:variables
}
