/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supsoluti;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.net.URL;
/**
 *
 * @author brenno.lima
 */
public class T_dll extends javax.swing.JInternalFrame {

    /**
     * Creates new form T_dll
     */
    public T_dll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTipo = new javax.swing.ButtonGroup();
        btnModelo = new javax.swing.ButtonGroup();
        btnSo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        visor = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelcaminho = new javax.swing.JLabel();
        jLabelcopia = new javax.swing.JLabel();
        jLabelOU = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnWindows = new javax.swing.JRadioButton();
        btnMac = new javax.swing.JRadioButton();
        btnLinux = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnSafenet = new javax.swing.JRadioButton();
        btnEpass = new javax.swing.JRadioButton();
        btnMorpho = new javax.swing.JRadioButton();
        btnOberthur = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("DLL's");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setMinimumSize(new java.awt.Dimension(430, 215));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/binario.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(2, 2, 210, 310);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        visor.setEditable(false);
        visor.setBackground(new java.awt.Color(255, 255, 255));
        visor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel5.add(visor);
        visor.setBounds(10, 10, 380, 30);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel5.add(btnLimpar);
        btnLimpar.setBounds(50, 100, 106, 34);

        btnCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/copiar.png"))); // NOI18N
        btnCopiar.setText("COPIAR");
        btnCopiar.setEnabled(false);
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCopiar);
        btnCopiar.setBounds(220, 100, 106, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Caminho: ");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(14, 50, 60, 15);

        jLabelcaminho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelcaminho.setForeground(new java.awt.Color(255, 51, 51));
        jLabelcaminho.setText("...");
        jPanel5.add(jLabelcaminho);
        jLabelcaminho.setBounds(70, 50, 320, 15);

        jLabelcopia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelcopia.setForeground(new java.awt.Color(0, 0, 204));
        jLabelcopia.setText("...");
        jPanel5.add(jLabelcopia);
        jLabelcopia.setBounds(10, 150, 340, 15);

        jLabelOU.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelOU.setForeground(new java.awt.Color(255, 51, 51));
        jLabelOU.setText("...");
        jPanel5.add(jLabelOU);
        jLabelOU.setBounds(20, 70, 370, 15);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(200, 130, 400, 170);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        btnWindows.setBackground(new java.awt.Color(255, 255, 255));
        btnSo.add(btnWindows);
        btnWindows.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnWindows.setText("WINDOWS");
        btnWindows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWindowsMouseClicked(evt);
            }
        });
        btnWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWindowsActionPerformed(evt);
            }
        });

        btnMac.setBackground(new java.awt.Color(255, 255, 255));
        btnSo.add(btnMac);
        btnMac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMac.setText("MAC");
        btnMac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMacMouseClicked(evt);
            }
        });
        btnMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacActionPerformed(evt);
            }
        });

        btnLinux.setBackground(new java.awt.Color(255, 255, 255));
        btnSo.add(btnLinux);
        btnLinux.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLinux.setText("LINUX");
        btnLinux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLinuxMouseClicked(evt);
            }
        });
        btnLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinuxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnWindows)
                .addGap(18, 18, 18)
                .addComponent(btnMac)
                .addGap(18, 18, 18)
                .addComponent(btnLinux)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWindows)
                    .addComponent(btnMac)
                    .addComponent(btnLinux))
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSafenet.setBackground(new java.awt.Color(255, 255, 255));
        btnModelo.add(btnSafenet);
        btnSafenet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSafenet.setText("SafeNet");
        btnSafenet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSafenetMouseClicked(evt);
            }
        });
        btnSafenet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafenetActionPerformed(evt);
            }
        });

        btnEpass.setBackground(new java.awt.Color(255, 255, 255));
        btnModelo.add(btnEpass);
        btnEpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEpass.setText("ePass2003");
        btnEpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEpassMouseClicked(evt);
            }
        });
        btnEpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEpassActionPerformed(evt);
            }
        });

        btnMorpho.setBackground(new java.awt.Color(255, 255, 255));
        btnModelo.add(btnMorpho);
        btnMorpho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMorpho.setText("Morpho");
        btnMorpho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMorphoMouseClicked(evt);
            }
        });
        btnMorpho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorphoActionPerformed(evt);
            }
        });
        btnMorpho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMorphoKeyPressed(evt);
            }
        });

        btnOberthur.setBackground(new java.awt.Color(255, 255, 255));
        btnModelo.add(btnOberthur);
        btnOberthur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOberthur.setText("Oberthur");
        btnOberthur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOberthurMouseClicked(evt);
            }
        });
        btnOberthur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOberthurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnSafenet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnMorpho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOberthur)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSafenet)
                    .addComponent(btnEpass)
                    .addComponent(btnMorpho)
                    .addComponent(btnOberthur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(200, 10, 400, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        btnTipo.clearSelection();
        btnModelo.clearSelection();
        btnSo.clearSelection();
        visor.setText("");
        jLabelcopia.setText("...");
        jLabelcaminho.setText("...");
        jLabelOU.setText("...");
        btnCopiar.setEnabled(false);
        btnLimpar.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed
    private void ativaBtn() {
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
    }
    
    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
        ClipboardOwner selecao = new StringSelection(visor.getText());
        board.setContents((Transferable) selecao, selecao);
        jLabelcopia.setText("Copiado com Exito!");
        btnCopiar.setEnabled(false);
    }//GEN-LAST:event_btnCopiarActionPerformed
    
    private void btnWindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWindowsMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnWindowsMouseClicked

    private void btnWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWindowsActionPerformed
        if (btnSafenet.isSelected()) {
            visor.setText("etoken.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\etoken.dll");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnEpass.isSelected()) {
            visor.setText("eps2003csp11.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\eps2003csp11.dll");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnMorpho.isSelected()) {
            visor.setText("aetpkss1.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\aetpkss1.dll");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnOberthur.isSelected()) {
            visor.setText("OcsCryptoki.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\OcsCryptoki.dll");
            jLabelOU.setText("C:\\Program Files\\Oberthur Technologies\\AWP\\DLLs\\OcsCryptoki.dll");
            ativaBtn();
        }
    }//GEN-LAST:event_btnWindowsActionPerformed

    private void btnMacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMacMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnMacMouseClicked

    private void btnMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacActionPerformed
        if (btnSafenet.isSelected()) {
            visor.setText("libeTPkcs11.dylib");
            jLabelcaminho.setText("/usr/local/lib/libeTPkcs11.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnEpass.isSelected()) {
            visor.setText("libcastle.1.0.0.dylib");
            jLabelcaminho.setText("/usr/local/lib/libcastle.1.0.0.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnMorpho.isSelected()) {
            visor.setText("libaetpkss.dylib");
            jLabelcaminho.setText("/usr/local/lib/libaetpkss.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnOberthur.isSelected()) {
            visor.setText("libOcsCryptoki.dylib");
            jLabelcaminho.setText("/usr/local/AWP/lib/libOcsCryptoki.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        }
    }//GEN-LAST:event_btnMacActionPerformed

    private void btnLinuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLinuxMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnLinuxMouseClicked

    private void btnLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinuxActionPerformed
        if (btnLinux.isSelected()) {
            if (btnSafenet.isSelected()) {
                visor.setText("libeTPkcs11.so");
                jLabelcaminho.setText("/usr/lib/libeTPkcs11.so");
                jLabelOU.setText("...");
                ativaBtn();
            } else if (btnEpass.isSelected()) {
                visor.setText("libcastle.so.1.0.0");
                jLabelcaminho.setText("/usr/lib/libcastle.so.1.0.0.so");
                jLabelOU.setText("...");
                ativaBtn();
            } else if (btnMorpho.isSelected()) {
                visor.setText("libaetpkss.so");
                jLabelcaminho.setText("/usr/lib/libaetpkss.so");
                jLabelOU.setText("...");
                ativaBtn();
            } else if (btnOberthur.isSelected()) {
                visor.setText("libOcsCryptoki.so");
                jLabelcaminho.setText("/usr/local/AWP/lib/libOcsCryptoki.so");
                jLabelOU.setText("...");
                ativaBtn();
            }
        }
    }//GEN-LAST:event_btnLinuxActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnSafenetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSafenetMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnSafenetMouseClicked

    private void btnSafenetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafenetActionPerformed
        if (btnLinux.isSelected()) {
            visor.setText("libeTPkcs11.so");
            jLabelcaminho.setText("/usr/lib/libeTPkcs11.so");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnMac.isSelected()) {
            visor.setText("libeTPkcs11.dylib");
            jLabelcaminho.setText("/usr/local/lib/libeTPkcs11.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnWindows.isSelected()) {
            visor.setText("etoken.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\etoken.dll");
            jLabelOU.setText("...");
            ativaBtn();
        }
    }//GEN-LAST:event_btnSafenetActionPerformed

    private void btnEpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEpassMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnEpassMouseClicked

    private void btnEpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEpassActionPerformed
        if (btnLinux.isSelected()) {
            visor.setText("libcastle.so.1.0.0.so");
            jLabelcaminho.setText("/usr/lib/libcastle.so.1.0.0.so");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnMac.isSelected()) {
            visor.setText("libcastle.1.0.0.dylib");
            jLabelcaminho.setText("/usr/local/lib/libcastle.1.0.0.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnWindows.isSelected()) {
            visor.setText("eps2003csp11.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\eps2003csp11.dll");
            jLabelOU.setText("...");
            ativaBtn();
        }
    }//GEN-LAST:event_btnEpassActionPerformed

    private void btnMorphoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMorphoMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnMorphoMouseClicked

    private void btnMorphoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorphoActionPerformed
        if (btnLinux.isSelected()) {
            visor.setText(" libaetpkss.so OU libetoken.so.9.1.7");
            jLabelcaminho.setText("/usr/lib/libaetpkss.so");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnMac.isSelected()) {
            visor.setText("libaetpkss.dylib");
            jLabelcaminho.setText("/usr/local/lib/libaetpkss.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnWindows.isSelected()) {
            visor.setText("aetpkss1.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\aetpkss1.dll");
            jLabelOU.setText("...");
            ativaBtn();
        }
    }//GEN-LAST:event_btnMorphoActionPerformed

    private void btnMorphoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMorphoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMorphoKeyPressed

    private void btnOberthurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOberthurMouseClicked
        jLabelcopia.setText("...");
    }//GEN-LAST:event_btnOberthurMouseClicked

    private void btnOberthurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOberthurActionPerformed
        if (btnLinux.isSelected()) {
            visor.setText("libOcsCryptoki.so");
            jLabelcaminho.setText("/usr/local/AWP/lib/libOcsCryptoki.so");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnMac.isSelected()) {
            visor.setText("libOcsCryptoki.dylib");
            jLabelcaminho.setText("/usr/local/AWP/lib/libOcsCryptoki.dylib");
            jLabelOU.setText("...");
            ativaBtn();
        } else if (btnWindows.isSelected()) {
            visor.setText("OcsCryptoki.dll");
            jLabelcaminho.setText("C:\\Windows\\System32\\OcsCryptoki.dll");
            jLabelOU.setText("C:\\Program Files\\Oberthur Technologies\\AWP\\DLLs\\OcsCryptoki.dll");
            ativaBtn();
        }
    }//GEN-LAST:event_btnOberthurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JRadioButton btnEpass;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JRadioButton btnLinux;
    private javax.swing.JRadioButton btnMac;
    private javax.swing.ButtonGroup btnModelo;
    private javax.swing.JRadioButton btnMorpho;
    private javax.swing.JRadioButton btnOberthur;
    private javax.swing.JRadioButton btnSafenet;
    private javax.swing.ButtonGroup btnSo;
    private javax.swing.ButtonGroup btnTipo;
    private javax.swing.JRadioButton btnWindows;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelOU;
    private javax.swing.JLabel jLabelcaminho;
    private javax.swing.JLabel jLabelcopia;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
