/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supsoluti;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

/**
 *
 * @author brenno.lima
 */
public class T_link_cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form T_link_cliente
     */
    public T_link_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTeste1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnTeste2 = new javax.swing.JButton();
        btnAssine = new javax.swing.JButton();
        btnTeste = new javax.swing.JButton();
        btnCertillion = new javax.swing.JButton();
        btnMozilla = new javax.swing.JButton();
        btnJava = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCopiar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        visor1 = new javax.swing.JTextPane();
        jLabel_copia = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Link's Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        btnTeste1.setText("Java Bloqueando");
        btnTeste1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeste1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTeste1);
        btnTeste1.setBounds(10, 10, 160, 40);

        jButton1.setText("Loja Kaspersky");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(180, 10, 160, 40);

        btnTeste2.setText(" Coleta Web - DBE ");
        btnTeste2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeste2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTeste2);
        btnTeste2.setBounds(180, 110, 160, 40);

        btnAssine.setText("Assine Online");
        btnAssine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssineActionPerformed(evt);
            }
        });
        jPanel2.add(btnAssine);
        btnAssine.setBounds(10, 160, 160, 40);

        btnTeste.setText("Teste de Baixa");
        btnTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesteActionPerformed(evt);
            }
        });
        jPanel2.add(btnTeste);
        btnTeste.setBounds(180, 60, 160, 40);

        btnCertillion.setText("Certillion ID");
        btnCertillion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertillionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCertillion);
        btnCertillion.setBounds(10, 110, 160, 40);

        btnMozilla.setText("Mozilla 41");
        btnMozilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMozillaActionPerformed(evt);
            }
        });
        jPanel2.add(btnMozilla);
        btnMozilla.setBounds(10, 60, 160, 40);

        btnJava.setText("Java");
        btnJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJavaActionPerformed(evt);
            }
        });
        jPanel2.add(btnJava);
        btnJava.setBounds(180, 160, 160, 40);

        jButton2.setText("Desinstalar java - MAC");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 210, 160, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 350, 260);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/copiar.png"))); // NOI18N
        btnCopiar.setText("COPIAR");
        btnCopiar.setEnabled(false);
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCopiar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 300, 890, 70);

        visor1.setEditable(false);
        jScrollPane2.setViewportView(visor1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 10, 530, 260);

        jLabel_copia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_copia.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_copia.setText("...");
        jPanel1.add(jLabel_copia);
        jLabel_copia.setBounds(290, 280, 360, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste1ActionPerformed
        visor1.setText("https://emissor.ca.inf.br\n" +
            "https://emissor.ca.inf.br:443\n" +
            "https://emissor.ca.inf.br:8080\n" +
            "http://emissor.ca.inf.br\n" +
            "http://emissor.ca.inf.br :443\n" +
            "http://emissor.ca.inf.br:8080");
        ativaBtn();
    }//GEN-LAST:event_btnTeste1ActionPerformed
    private void ativaBtn() {
        btnCopiar.setEnabled(true);
        btnLimpar.setEnabled(true);
        jLabel_copia.setText("...");
    }        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        visor1.setText("https://loja.certificadodigital.com/antivirus.html");
        ativaBtn();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTeste2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste2ActionPerformed
        visor1.setText("https://www38.receita.fazenda.gov.br/cadsincnac/jsp/coleta/ajuda/certificado/instrucoes_applet.html \n" +
            "  \n" +
            "http://www.contabeis.com.br/forum/topicos/240715/coleta-web-dbe-erro-inesperado-null/1");
        ativaBtn();
    }//GEN-LAST:event_btnTeste2ActionPerformed

    private void btnAssineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssineActionPerformed
        visor1.setText("https://assine.online/#/");
        ativaBtn();
    }//GEN-LAST:event_btnAssineActionPerformed

    private void btnTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesteActionPerformed
        visor1.setText("http://ccd.acsoluti.com.br/lcr/ac-soluti-multipla-v1.p7b");
        ativaBtn();
    }//GEN-LAST:event_btnTesteActionPerformed

    private void btnCertillionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertillionActionPerformed
        visor1.setText("https://emissor.certillionid.com/#/app/certificado/emissor/1");
        ativaBtn();
    }//GEN-LAST:event_btnCertillionActionPerformed

    private void btnMozillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMozillaActionPerformed
        visor1.setText("https://releases.mozilla.org/pub/firefox/releases/41.0.2/win32/pt-BR/Firefox%20Setup%2041.0.2.exe");
        ativaBtn();
    }//GEN-LAST:event_btnMozillaActionPerformed

    private void btnJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJavaActionPerformed
        visor1.setText("https://www.java.com/pt_BR/download/manual.jsp");
        ativaBtn();
    }//GEN-LAST:event_btnJavaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        visor1.setText("1. Clique no ícone do Finder.\n"
            + "2. Clique em Ir no menu do Finder.\n"
            + "3. Clique em Utilitários.\n"
            + "4. Clique duas vezes no ícone do Terminal.\n"
            + "5. Na janela Terminal, copie e cole os comandos abaixo:\n"
            + "\n"
            + "sudo rm -fr /Library/Internet\\ Plug-Ins/JavaAppletPlugin.plugin\n"
            + "sudo rm -fr /Library/PreferencePanes/JavaControlPanel.prefPane\n"
            + "sudo rm -fr ~/Library/Application\\ Support/Oracle/Java\n"
            + "\n"
            + "Não tente desinstalar o Java removendo as ferramentas Java de / usr / bin."
            + "Este diretório faz parte do software do sistema e todas as alterações serão redefinidas pela Apple na próxima vez que você"
            + "executar uma atualização do sistema operacional.\n"
            + "\n"
            + "Duvidas: https://www.java.com/en/download/help/mac_uninstall_java.xml");
        ativaBtn();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
        ClipboardOwner selecao = new StringSelection(visor1.getText());
        board.setContents((Transferable) selecao, selecao);
        jLabel_copia.setText("Copiado com Exito!");
        btnCopiar.setEnabled(false);
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        visor1.setText("");
        btnCopiar.setEnabled(false);
        btnLimpar.setEnabled(false);
        ativaBtn();
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssine;
    private javax.swing.JButton btnCertillion;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnJava;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMozilla;
    private javax.swing.JButton btnTeste;
    private javax.swing.JButton btnTeste1;
    private javax.swing.JButton btnTeste2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_copia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane visor1;
    // End of variables declaration//GEN-END:variables
}
