/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supsoluti;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author brenno.lima
 */
public class T_sobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form T_sobre
     */
    public T_sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sobre");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Desenvolvido por:"));
        jPanel5.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Brenno Marques de Lima");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(80, 20, 151, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("brenno.marquesb@gmail.com");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(90, 100, 180, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("(62) 9 9909-5716");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(86, 60, 130, 15);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/call_30x.png"))); // NOI18N
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 50, 30, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/whatsapp_30x.png"))); // NOI18N
        jPanel5.add(jLabel24);
        jLabel24.setBounds(40, 50, 30, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/e-mail_30x.png"))); // NOI18N
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 90, 30, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Desenvolvido por:"));
        jPanel6.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Alexandre Siva de Almeida");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(80, 20, 161, 15);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("asa-008@hotmail.com");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(90, 100, 150, 15);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("(62) 9 8275-8468");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(86, 60, 130, 15);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/call_30x.png"))); // NOI18N
        jPanel6.add(jLabel29);
        jLabel29.setBounds(10, 50, 30, 30);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/whatsapp_30x.png"))); // NOI18N
        jPanel6.add(jLabel30);
        jLabel30.setBounds(40, 50, 30, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/e-mail_30x.png"))); // NOI18N
        jPanel6.add(jLabel31);
        jLabel31.setBounds(10, 90, 30, 30);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sobre.PNG"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Soluti_2_50x50.png"))); // NOI18N
        jButton1.setText("Site Soluti");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(-3);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Soluti_3_25x25.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Soluti_1_80x80.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 120, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );

        setBounds(0, 0, 643, 277);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://www.soluti.com.br/"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(T_link_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
